[tool.poetry]
name = "declarai"
version = "0.1.0"
description = ""
authors = ["Aviv Almashanu <avivex1000@gmail.com>"]
readme = "README.md"
packages = [{include = "declarai"}]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.8"
pydantic = "^1"


[tool.poetry.group.dev.dependencies]
pylint = "^2.17.4"
black = "^23.7.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
