site_name: Declarai
nav:
- Declarai: index.md
- Beginners guide:
  - src/beginners-guide/index.md
  - Simple task: src/beginners-guide/simple-task.md
  - Controlling task behavior: src/beginners-guide/controlling-task-behavior.md
  - Debugging tasks: src/beginners-guide/debugging-tasks.md
  - Recap: src/beginners-guide/recap.md
- Advanced:
  - src/advanced/index.md
  - magic: src/advanced/magic.md
  - multiple provides: src/advanced/multiple_provides.md
  - middlewares:
    - src/advanced/middlewares/index.md
    - monitoring: src/advanced/middlewares/monitoring.md
  - Evals:
      - src/advanced/evals/index.md
- Providers:
  - src/providers/index.md
  - src/providers/openai.md
- integrations:
  - src/integrations/index.md
- Changelog: src/changelog.md
- Contribute : src/contribute.md

theme:
    features:
      - tabs
      - content.tooltips
      - content.code.copy
      - content.code.annotate
      - navigation.indexes
    name: material
    logo: img/Vendi-logo.svg
extra_css:
- css/extra.css
- css/termynal.css
extra_javascript:
- js/termynal.js
- js/custom.js
- js/tablesort.js
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
repo_url: https://github.com/vendi-ai/declarai
repo_name: vendi-ai/declarai
markdown_extensions:
- attr_list
- md_in_html
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.extra
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true
